# Generated by Django 2.2 on 2021-01-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20210117_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
    ]
